### ISSUE TITLE
Ansible paybook error 404 on download gophish

### ISSUE THREAD

**Issue by sbnsec** [gophish/gophish#1793]
What version of Gophish are you using?: 
0.9.0/branch master

Brief description of the issue: 
On the ansible repository when trying to download the latest gophish zip file 

What are you expecting to see happen? :
The file should be downloaded

What are you seeing happen?
```json
 {"response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://getgophish.com/releases/latest/linux/64"}
```

The error is located in the file :
https://github.com/gophish/gophish/blob/master/ansible-playbook/roles/gophish/tasks/main.yml
```yml
- name: Download latest Gophish .zip file.
  get_url:
    validate_certs: True
    url: https://getgophish.com/releases/latest/linux/64
    dest: "/home/{{ gophish_user }}/gophish.zip"
    mode: 0755
    owner: "{{ gophish_user }}"
    group: "{{ gophish_user }}"
```

Please provide as many steps as you can to reproduce the problem:
Launch the playbook

**Comment by jordan-wright** [comment]
Thanks for reporting this! This wasn’t a bug in Ansible, rather in DNS.

Last night, I had moved the domains into a new Cloudflare account. One of my page rules in cloudflare is this redirect. I had messed up the ordering so this wasn’t getting processed.

Should be all fixed now! Let me know if you run into any other issues. Sorry for the hassle!

**Comment by sbnsec** [comment]
Thanks for the fix, it's working again for me 👍 

 just FYI : I made a DIY fix to get the latest version :
```yml
- name: Get Gophish latest releases information
  uri:                                                               
    url: https://api.github.com/repos/gophish/gophish/releases/latest
    return_content: true                                             
  register: json_reponse                                             

- name: Parse the response to get the latest verion URL
  get_url:
    url: "{{ json_reponse.json.assets | to_json | from_json | json_query(jq) | join('#') }}"
    dest: ./gophish.zip
```
with the JQ var :

```yml
jq: "[?contains(browser_download_url, 'linux-64bit.zip')].browser_download_url"
```

Have a nice day!
