### ISSUE TITLE
cannot start gophish

### ISSUE THREAD

**Issue by marnysan111** [gophish/gophish#1953]
Hello,I`m Japanese Students
I can`t start gophish

help me!

**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
> 20200730000000
Brief description of the issue: 
>cannot start gophish

I ran these commands

```
# go get github.com/gophish/gophish
# cd $GOPATH/src/github.com/gophish/gophish
# go build
# gophish
time="2020-08-30T02:02:24+09:00" level=warning msg="No contact address has been configured."
time="2020-08-30T02:02:24+09:00" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20200730000000
time="2020-08-30T02:02:24+09:00" level=info msg="Please login with the username admin and the password 75a2d62bfcd6a32e"
time="2020-08-30T02:02:24+09:00" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2020-08-30T02:02:24+09:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2020-08-30T02:02:24+09:00" level=info msg="Starting IMAP monitor manager"
time="2020-08-30T02:02:24+09:00" level=info msg="Starting new IMAP monitor for user admin"
time="2020-08-30T02:02:24+09:00" level=info msg="Starting phishing server at http://0.0.0.0:80"
^Ctime="2020-08-30T02:02:53+09:00" level=info msg="CTRL+C Received... Gracefully shutting down servers"
time="2020-08-30T02:02:53+09:00" level=info msg="Shutting down IMAP monitor manager"
```
Then I visited 192.168.56.1:80
'''
404 page not found

\"GET / HTTP/1.1\" 404 19 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
'''

Then I visited 192.168.56.1:3333
```
I cannot access this site
```

What are you expecting to see happen? :
>I do not know

What are you seeing happen?
>What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
OS:centos7.6.1810
# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources:
  services: ssh dhcpv6-client samba http https
  ports: 3333/tcp 8080/tcp 80/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

Please provide as many steps as you can to reproduce the problem:

 * Step 1 -  # go get github.com/gophish/gophish
 * Step 2 -  # cd $GOPATH/src/github.com/gophish/gophish
 * Step 3 -  # go byuld
 * Step 4 -  # gophish
 
 
I'm not good at English, but thank you
