### ISSUE TITLE
GoPhish behind NGINX Ingress

### ISSUE THREAD

**Issue by AbderrahimBouhdida** [gophish/gophish#2843]
What version of Gophish are you using?:  0.11.0

Brief description of the issue: When deploying GoPhish on a kubernetes cluster and exposing it with a Nginx Ingress the admin login page loads up but when pressing logins in shows "Forbidden - referer invalid" 

What are you expecting to see happen? : the dashboard

What are you seeing happen? "Forbidden - referer invalid"

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Deploy on a kubernetes cluster
 * Step 2 - Expose it through NGINX Ingress 
 
These are the config files 
Gophish config :
``` 
{
  "admin_server": {
    "listen_url": "0.0.0.0:3333",
    "use_tls": true,
    "cert_path": "/etc/ssl/crt/gophish.crt",
    "key_path": "/etc/ssl/private/gophish.pem",
    "trusted_origins": ["xxxxx.com"]
  },
  "phish_server": {
    "listen_url": "0.0.0.0:8080",
    "use_tls": true,
    "cert_path": "/etc/ssl/crt/gophish.crt",
    "key_path": "/etc/ssl/private/gophish.pem"
  },
  "db_name": "sqlite3",
  "db_path": "gophish.db",
  "migrations_prefix": "db/db_",
  "contact_address": "",
  "logging": {
    "filename": "gophish.log",
    "level": ""
  }
}

```
Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trawler-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_ssl_verify   off;
      proxy_set_header   X-Real-IP          $remote_addr;
      proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.org/client-max-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - xxxxx.com
    secretName: cert-testing
  rules:
  - host: xxxxx.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: xxxxx-svc
            port:
              number: 3333
```

**Comment by SalahBellagnaoui** [comment]
hello @AbderrahimBouhdida, im facing the same probleme, how were you able to solve it pls ?

**Comment by cyberpeacetest** [comment]
hello 

i have exactly the same issue , does someone got a fix ?
thanks

**Comment by nicolas-san** [comment]
hello, 
does somebody have a working ingress to use gophish in k8s ?
@sn0b4ll maybe ?

**Comment by sn0b4ll** [comment]
@nicolas-san that is the config I used about a year ago - pls don't pin me down on if it's working, I sadly don't the have environment to test it

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gophish-ingress
  annotations:
    INGRESS.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gophish-service
            port:
              number: 3333
```
